from migrate_test_to_prod.migrate_invoices import migrate_invoices_to_prod
from migrate_test_to_prod.migrate_organizations import migrate_organization_to_prod

# migrate_invoices_to_prod()
# migrate_organization_to_prod()